name: docusign_flutter_sdk_generator
description: OpenAPI Generator for DocuSign APIs
version: 0.0.1
homepage: https://github.com/GiamBoscaro/docusign-sdk-openapi-generator
documentation: https://github.com/GiamBoscaro/docusign-sdk-openapi-generator#readme
repository: https://github.com/GiamBoscaro/docusign-sdk-openapi-generator

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  openapi_generator_annotations: ^4.0.0

dependency_overrides:
  analyzer: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  openapi_generator: ^4.0.0
  copywriter: ^2.0.0
flutter:
